### PR TITLE
Remove some options that seem to cause problems in recent versions

### PR DESCRIPTION
**Pull request by floer32**
Using 2020.03 of JetBrains IDEs, I tried with two (IntelliJ and Rubymine) and found that they wouldn't boot anymore, until I removed some properties. I didn't bisect each and every one, but removing the garbage collector related properties (`GC`) did the trick for me.

### CODE REVIEW

**Comment by pkozuchowski** [comment]
@hangtwenty I've tried VM options from the PR and IntelliJ still wouldn't boot

**Comment by floer32** [comment]
@amorek bummer! i'm not sure then

**Comment by pkozuchowski** [comment]
This is what I've got after removing lines that were causing issues for me:
```
-server
-Xms1g
-Xmx4g
-XX:NewSize=512m
-XX:MaxNewSize=512m
-XX:PermSize=512m
-XX:MaxPermSize=512m
-XX:ParallelGCThreads=8
-XX:MaxTenuringThreshold=1
-XX:SurvivorRatio=8
-XX:+UseCodeCacheFlushing
-XX:+UseConcMarkSweepGC
-XX:+AggressiveOpts
-XX:ReservedCodeCacheSize=256m
-XX:-TraceClassUnloading
-ea
-Dsun.io.useCanonCaches=false
```

**Comment by Maczuga** [comment]
Following one is working with WebStorm 2021.1.1

```
-Xms1024m
-Xmx3072m
-Xss64m
-XX:ReservedCodeCacheSize=512m
-XX:+UseCompressedOops
-XX:NewRatio=2
-Dfile.encoding=UTF-8
-XX:+UseConcMarkSweepGC
-XX:SoftRefLRUPolicyMSPerMB=250
-XX:NewSize=512m
-XX:MaxNewSize=512m
-XX:PermSize=512m
-XX:MaxPermSize=1024m
-XX:ParallelGCThreads=4
-XX:MaxTenuringThreshold=1
-XX:SurvivorRatio=8
-XX:+UseCodeCacheFlushing
-XX:+AggressiveOpts
-XX:+CMSClassUnloadingEnabled
-XX:+CMSParallelRemarkEnabled
-XX:CMSInitiatingOccupancyFraction=65
-XX:+CMSScavengeBeforeRemark
-XX:+UseCMSInitiatingOccupancyOnly
-XX:-TraceClassUnloading
-XX:+AlwaysPreTouch
-XX:+TieredCompilation
-XX:+DoEscapeAnalysis
-XX:+UnlockExperimentalVMOptions
-XX:LargePageSizeInBytes=256m
-XX:+DisableExplicitGC
-XX:+ExplicitGCInvokesConcurrent
-XX:+PrintGCDetails
-XX:+PrintFlagsFinal
-XX:+HeapDumpOnOutOfMemoryError
-XX:CompileThreshold=10000
-XX:+OptimizeStringConcat
-XX:+UnlockDiagnosticVMOptions
-ea
-Dsun.io.useCanonCaches=false
-Djava.net.preferIPv4Stack=true
-XX:-OmitStackTraceInFastThrow
-Xverify:none

-XX:ErrorFile=$USER_HOME/java_error_in_idea_%p.log
-XX:HeapDumpPath=$USER_HOME/java_error_in_idea.hprof
-Dide.no.platform.update=true
```

Diff: https://www.diffchecker.com/dQ7uKkoQ

**Comment by ScriptedAlchemy** [comment]
Please open more PRs if this PR does not solve the problems.

**Pull request merged**
